project_name: "multi-repository-analyzer"

languages:
  - typescript

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

included_optional_tools: []

fixed_tools: []

base_modes:

default_modes:

initial_prompt: ""
